common:
  ports: [
    5432, 5433, 5434, 5435, 5436, 5437
  ]
  db_metric_ports: [
      55432, 55433, 55434, 55435, 55436, 55437
  ]
  architecture: amd64
  projectDir: <PROJECT_DIR>
  client_id: <CLIENT_ID> #optional
  client_secret: <CLIENT_SECRET> #optional
  api_key: <API_KEY> #if not using github authentication